### ISSUE TITLE
[Question] Where to get PIXIV_CLIENT_ID and PIXIV_CLIENT_SECRET?

### ISSUE THREAD

**Issue by yogthot** [pixiv/passport-pixiv#1]
I've searched around but couldn't find any way to register an app or get these values in any way.
All I found were several unofficial methods  of authentication, but that might just put people's accounts/passwords at risk.

If there's an official way to get the `client_id` and `client_secret` values, I think it'd be a good idea to have it somewhere in the README, since this is the first result on google for "pixiv OAuth".

**Comment by geta6** [comment]
Hi @Patchonn , thank you for your interest to our repo. 
Currently, pixiv doesn't issue keys and tokens for oAuth to 3rd parties.

**Comment by yogthot** [comment]
Thank you for your reply.

For now I'll try looking for another way to solve my problem.
I hope pixiv can support 3rd-party apps someday.
